theme:
  defaultMode: auto
  light:
    canvasBackground: '#ffffff'
    bodyBackground: '#f8f9fa'
    panelBackground: rgba(255, 255, 255, 0.95)
    panelBackgroundSecondary: rgba(248, 249, 250, 0.9)
    headerBackground: '#ffffff'
    textPrimary: '#212529'
    textSecondary: '#6c757d'
    textMuted: '#adb5bd'
    textInverse: '#ffffff'
    borderPrimary: '#dee2e6'
    borderSecondary: '#e9ecef'
    borderAccent: '#007bff'
    edgeColor: '#cccccc'
    success: '#28a745'
    warning: '#ffc107'
    error: '#dc3545'
    info: '#17a2b8'
  dark:
    canvasBackground: '#1a1a1a'
    bodyBackground: '#0d1117'
    panelBackground: rgba(30, 30, 30, 0.95)
    panelBackgroundSecondary: rgba(20, 20, 20, 0.9)
    headerBackground: '#161b22'
    textPrimary: '#f0f6fc'
    textSecondary: '#8b949e'
    textMuted: '#6e7681'
    textInverse: '#0d1117'
    borderPrimary: '#30363d'
    borderSecondary: '#21262d'
    borderAccent: '#58a6ff'
    edgeColor: '#444444'
    success: '#3fb950'
    warning: '#d29922'
    error: '#f85149'
    info: '#79c0ff'
visual:
  nodes:
    defaultSize: 1
    defaultColor: '#888888'
    minSize: 0.5
    maxSize: 5
    minSpacing: 100  # Minimum spacing between nodes in coordinate units
    overlapBehavior: 'jitter'  # How to handle overlapping nodes: 'none', 'jitter', or 'spread'
  edges:
    defaultSize: 1
    defaultColor: '#cccccc'
    minSize: 0.1
    maxSize: 5
  labels:
    enabled: true
    renderThreshold: 0.01  # Camera ratio threshold for rendering labels
    hideOnMove: false
    density: 0.7
    gridCellSize: 100
    sizeThreshold: 8
  search:
    focusNodeColor: '#ff6b6b'
    focusNodeSize: 15
    neighborNodeColor: '#4ecdc4'
    neighborNodeSize: 10
    focusEdgeColor: '#ff8e53'
    focusEdgeSize: 3
lod:
  thresholds:
    universe: 10.0    # Universe view (zoomed way out)
    field: 6.0       # Field view
    topic: 3.0       # Topic view
    paper: 0.1       # Paper view (zoomed in) - Lowered to allow closer zooming
  maxNodes:
    universe: 10000   # A few hundred nodes across the whole graph
    field: 10000     # Trunk of each discipline
    topic: 10000     # Sub-branches with cross-links
    paper: 10000      # Everything in viewport
  minDegree:
    universe: 1     # High-degree nodes only
    field: 1       # Major papers
    topic: 1       # Important papers
    paper: 1       # All papers
  loadEdges:
    universe: true  # Just dots
    field: true    # Tree edges only
    topic: true    # Tree + extra edges
    paper: true    # All edges
  edgeTypes:
    universe: "none"
    field: "tree"
    topic: "tree+extra"
    paper: "all"
performance:
  cache:
    ttl: 10000
    maxRegions: 100
    overlapThreshold: 0.5
    spatialHashSize: 50
  loading:
    batchSize: 100
    maxBatchSize: 1000
    minBatchSize: 50
    adaptiveBatching: true
    earlyTermination: true
    maxEmptyBatches: 2
    smartTermination: true
    maxConcurrentBatches: 3
  api:
    timeout: 10000
    maxRetries: 3
    retryDelay: 1000
viewport:
  initialRatio: 1.0
  minCameraRatio: 0.001  # Lowered to allow much closer zooming
  maxCameraRatio: 20
  paddingFactor: 0.1
  coordinateScale: 1000.0  # Reduced to spread out nodes more
  initialBounds:
    xMin: -1000
    xMax: 1000
    yMin: -1000
    yMax: 1000
    note: Updated to match actual data range
memory:
  maxTotalNodes: 10000
  maxTotalEdges: 20000
  cleanupThreshold: 0.8
  aggressiveCleanup: false
  viewportNodeRatio: 0.7
  spatialOptimization:
    enabled: true
    rTreeMaxEntries: 16
    rTreeMinEntries: 4
    viewportPadding: 1.5
    distanceThreshold: 3.0
    lastSeenThreshold: 30000
    maxViewportNodes: 2000
    maxDistantNodes: 1000
    spatialCleanupInterval: 5000
    performanceCleanupInterval: 10000
    enableNodeHiding: true
    hideDistanceThreshold: 5.0
    maxHiddenNodes: 5000
    maxSpatialRegions: 200
    regionMergeThreshold: 0.3
    enablePerformanceMonitoring: true
    targetFrameRate: 30
    frameRateWindow: 60
interaction:
  dragThreshold: 5
  panSensitivity: 1.0
  searchCacheSize: 50
  searchTimeout: 5000
debug:
  enableLODLogging: true
  enableEdgeLogging: true
  enableCacheLogging: false
  enablePerformanceLogging: true
  slowQueryThreshold: 2000
  memoryCheckInterval: 30000
backend:
  defaultNodeLimit: 5000
  defaultEdgeLimit: 3000
  maxNodeLimit: 10000
  maxEdgeLimit: 50000
  spatialIndexing: true
  degreeIndexing: true
